#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppDrinkAndroid.Resource", IsApplication=true)]

namespace AppDrinkAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int menu = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int agregarFoto = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int agregarTrago = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int candado = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int candadoAbierto = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int drinkDefault = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tuerca = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int btCancelar = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int btGuardar = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int btIngresar = 2131099658;
			
			// aapt resource value: 0x7f060024
			public const int btnDone = 2131099684;
			
			// aapt resource value: 0x7f060003
			public const int checkBoxIngrendientes = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int checkBoxPrecio = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int etIngredientes = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int etNombre = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int etPrecio = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int imgBtnAgregarFoto = 2131099664;
			
			// aapt resource value: 0x7f060019
			public const int imgBtnAgregarTrago = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int imgBtnCandado = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int imgBtnTuerca = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int imgLogo = 2131099670;
			
			// aapt resource value: 0x7f06000f
			public const int imgViewDrinkCapture = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int imgViewDrinkImage = 2131099665;
			
			// aapt resource value: 0x7f060020
			public const int lblCategoria = 2131099680;
			
			// aapt resource value: 0x7f06001e
			public const int lblIngredientes = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int lblNombre_ = 2131099677;
			
			// aapt resource value: 0x7f060022
			public const int lblPass = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int lblPrecio = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int lblWelcome = 2131099681;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f06001c
			public const int listViewDrinks = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int spinner = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int spinnerCategoria = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int spinnerLabel = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int tvCategoria = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int tvIngredientes = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int tvNombre = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int tvPrecio = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int txtIncorrecta = 2131099657;
			
			// aapt resource value: 0x7f060023
			public const int txtPass = 2131099683;
			
			// aapt resource value: 0x7f060008
			public const int txtPassword = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int txtTitulo = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int txtTitulo2 = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int txtTrago = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Configuracion = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Contrasena = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DrinkEdit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DrinkListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ViewDrink = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Welcome = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int btnCancelar = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int btnGuardar = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int categorias = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ingreseIngredientes = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ingreseNombre = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int ingresePrecio = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
