#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppDrinkAndroid.Resource", IsApplication=true)]

namespace AppDrinkAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int agregarFoto = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int agregarTrago = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int candado = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drinkDefault = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tuerca = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btCancelar = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int btGuardar = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int btIngresar = 2131034122;
			
			// aapt resource value: 0x7f050020
			public const int btnDone = 2131034144;
			
			// aapt resource value: 0x7f050003
			public const int checkBoxIngrendientes = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int checkBoxPrecio = 2131034114;
			
			// aapt resource value: 0x7f05000c
			public const int etIngredientes = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int etNombre = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int etPrecio = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int imgBtnAgregarFoto = 2131034128;
			
			// aapt resource value: 0x7f050019
			public const int imgBtnAgregarTrago = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int imgBtnCandado = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int imgBtnTuerca = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int imgLogo = 2131034134;
			
			// aapt resource value: 0x7f05000f
			public const int imgViewDrinkCapture = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int imgViewDrinkImage = 2131034129;
			
			// aapt resource value: 0x7f05001e
			public const int lblPass = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int lblWelcome = 2131034141;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f05001c
			public const int listViewDrinks = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int spinner = 2131034139;
			
			// aapt resource value: 0x7f05000e
			public const int spinnerCategoria = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int spinnerLabel = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int tvCategoria = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int tvIngredientes = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int tvNombre = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int tvPrecio = 2131034133;
			
			// aapt resource value: 0x7f050009
			public const int txtIncorrecta = 2131034121;
			
			// aapt resource value: 0x7f05001f
			public const int txtPass = 2131034143;
			
			// aapt resource value: 0x7f050008
			public const int txtPassword = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int txtTitulo = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int txtTitulo2 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int txtTrago = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Configuracion = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Contrasena = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DrinkEdit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DrinkListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Welcome = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int btnCancelar = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int btnGuardar = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int categorias = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ingreseIngredientes = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int ingreseNombre = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int ingresePrecio = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
